hpc <- read.table("hpc.txt", sep = ";", header = TRUE)
hpc$Date <- as.Date(hpc$Date, format = "%d/%m/%Y")
hpc <- subset(hpc, Date == "2007-02-01" | Date == "2007-02-02")
hpc$Global_active_power <- as.numeric(hpc$Global_active_power)
hpc$Global_active_power <- hpc$Global_active_power/1000
hpc$Time <- paste(hpc$Date, hpc$Time, sep = " ")
hpc$Time <- strptime(hpc$Time, format = "%Y-%m-%d %H:%M:%S")
par(mfrow = c(2,2))
plot(hpc$Time, hpc$Global_active_power, type = "l", ylab = "Global Active Power (Kilowatts)", xlab = "")
plot(hpc$Time, hpc$Voltage, xlab = "datetime", ylab = "Voltage", type = "l")
plot(hpc$Time, hpc$Sub_metering_1, type = "l", xlab = "", ylab = "Energy Sub metering")
lines(hpc$Time, hpc$Sub_metering_2, type = "l", col = "red")
lines(hpc$Time, hpc$Sub_metering_3, type = "l", col = "blue")
lables <- c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3")
legend("topright", inset = 0.01, lables, lwd = 1, col = c("black", "red", "blue"), bty = "n")
plot(hpc$Time, hpc$Global_reactive_power, xlab = "datetime", ylab = "Global_reactive_power", type = "l")
dev.copy(png, "plot4.png")
dev.off()