hpc <- read.table("hpc.txt", sep = ";", header = TRUE)
hpc$Date <- as.Date(hpc$Date, format = "%d/%m/%Y")
hpc <- subset(hpc, Date == "2007-02-01" | Date == "2007-02-02")
hpc$Global_active_power <- as.numeric(hpc$Global_active_power)
hpc$Global_active_power <- hpc$Global_active_power/1000
hpc$Time <- paste(hpc$Date, hpc$Time, sep = " ")
hpc$Time <- strptime(hpc$Time, format = "%Y-%m-%d %H:%M:%S")
plot(hpc$Time, hpc$Sub_metering_1, type = "l", xlab = "", ylab = "Energy Sub metering")
lines(hpc$Time, hpc$Sub_metering_2, type = "l", col = "red")
lines(hpc$Time, hpc$Sub_metering_3, type = "l", col = "blue")
lables <- c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3")
legend("topright", inset = 0.05, lables, lwd = 1, col = c("black", "red", "blue"))
dev.copy(png, "plot3.png")
dev.off()