hpc <- read.table("hpc.txt", sep = ";", header = TRUE)
hpc$Date <- as.Date(hpc$Date, format = "%d/%m/%Y")
hpc <- subset(hpc, Date == "2007-02-01" | Date == "2007-02-02")
hpc$Global_active_power <- as.numeric(hpc$Global_active_power)
hpc$Global_active_power <- hpc$Global_active_power/1000
hpc$Time <- paste(hpc$Date, hpc$Time, sep = " ")
hpc$Time <- strptime(hpc$Time, format = "%Y-%m-%d %H:%M:%S")
plot(hpc$Time, hpc$Global_active_power, type = "l", ylab = "Global Active Power (Kilowatts)", xlab = "")
dev.copy(png, "plot2.png")
dev.off()